#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    if [[ $1 == "-s" ]]; then
	selected=$(find ~/development/springscs -mindepth 1 -maxdepth 1 -type d | fzf)
    elif [[ $1 == "-p" ]]; then
	selected=$(find ~/development/personal -mindepth 1 -maxdepth 1 -type d | fzf)
    elif [[ $1 == "-r" ]]; then
	selected=$(find ~/development/public_repos -mindepth 1 -maxdepth 1 -type d | fzf)
    elif [[ $1 == "-a" ]]; then
	selected=$(find ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
    elif [[ $1 == "-d" ]]; then
	selected=$(find ~/development -mindepth 1 -maxdepth 1 -type d | fzf)
    else
    	selected=$1
    fi
else
    selected=$(find ~/development/springscs ~/development/personal ~/development/public_repos ~/ -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name

