#!/bin/bash

tmux list-windows -a -F "#S:#I:#W" | fzf \
    --delimiter=: \
    --preview 'tmux capture-pane -p -t {1}:{2} -S -100' \
    --preview-window=down:50% \
| {
    IFS=: read session window _
    tmux switch-client -t "$session"
    tmux select-window -t "$window"
}

